/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Angles describing the attitude (Euler angles) of a UxV */
@org.apache.avro.specific.AvroGenerated
public class Attitude extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 851763614791715478L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Attitude\",\"namespace\":\"eu.rawfie.uxv\",\"doc\":\"Angles describing the attitude (Euler angles) of a UxV\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"Header\",\"fields\":[{\"name\":\"sourceSystem\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Canonical name of the originating system\"},{\"name\":\"sourceModule\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Canonical name of the module within a given system that originated the message\"},{\"name\":\"time\",\"type\":\"long\",\"doc\":\"Time elapsed since the Unix epoch\",\"unit\":\"ms\"}]}},{\"name\":\"phi\",\"type\":\"float\",\"doc\":\"Rotation around the body's longitudinal axis\",\"unit\":\"rad\",\"min\":-3.141592653589793,\"max\":3.141592653589793},{\"name\":\"theta\",\"type\":\"float\",\"doc\":\"Rotation around the body's lateral or transverse axis\",\"unit\":\"rad\",\"min\":-1.570796326794897,\"max\":1.570796326794897},{\"name\":\"psi\",\"type\":\"float\",\"doc\":\"Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north\",\"unit\":\"rad\",\"min\":-3.141592653589793,\"max\":3.141592653589793}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public eu.rawfie.uxv.Header header;
  /** Rotation around the body's longitudinal axis */
   public float phi;
  /** Rotation around the body's lateral or transverse axis */
   public float theta;
  /** Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north */
   public float psi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Attitude() {}

  /**
   * All-args constructor.
   * @param header The new value for header
   * @param phi Rotation around the body's longitudinal axis
   * @param theta Rotation around the body's lateral or transverse axis
   * @param psi Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
   */
  public Attitude(eu.rawfie.uxv.Header header, java.lang.Float phi, java.lang.Float theta, java.lang.Float psi) {
    this.header = header;
    this.phi = phi;
    this.theta = theta;
    this.psi = psi;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    case 1: return phi;
    case 2: return theta;
    case 3: return psi;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (eu.rawfie.uxv.Header)value$; break;
    case 1: phi = (java.lang.Float)value$; break;
    case 2: theta = (java.lang.Float)value$; break;
    case 3: psi = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'header' field.
   * @return The value of the 'header' field.
   */
  public eu.rawfie.uxv.Header getHeader() {
    return header;
  }

  /**
   * Sets the value of the 'header' field.
   * @param value the value to set.
   */
  public void setHeader(eu.rawfie.uxv.Header value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'phi' field.
   * @return Rotation around the body's longitudinal axis
   */
  public java.lang.Float getPhi() {
    return phi;
  }

  /**
   * Sets the value of the 'phi' field.
   * Rotation around the body's longitudinal axis
   * @param value the value to set.
   */
  public void setPhi(java.lang.Float value) {
    this.phi = value;
  }

  /**
   * Gets the value of the 'theta' field.
   * @return Rotation around the body's lateral or transverse axis
   */
  public java.lang.Float getTheta() {
    return theta;
  }

  /**
   * Sets the value of the 'theta' field.
   * Rotation around the body's lateral or transverse axis
   * @param value the value to set.
   */
  public void setTheta(java.lang.Float value) {
    this.theta = value;
  }

  /**
   * Gets the value of the 'psi' field.
   * @return Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
   */
  public java.lang.Float getPsi() {
    return psi;
  }

  /**
   * Sets the value of the 'psi' field.
   * Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
   * @param value the value to set.
   */
  public void setPsi(java.lang.Float value) {
    this.psi = value;
  }

  /**
   * Creates a new Attitude RecordBuilder.
   * @return A new Attitude RecordBuilder
   */
  public static eu.rawfie.uxv.Attitude.Builder newBuilder() {
    return new eu.rawfie.uxv.Attitude.Builder();
  }

  /**
   * Creates a new Attitude RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Attitude RecordBuilder
   */
  public static eu.rawfie.uxv.Attitude.Builder newBuilder(eu.rawfie.uxv.Attitude.Builder other) {
    return new eu.rawfie.uxv.Attitude.Builder(other);
  }

  /**
   * Creates a new Attitude RecordBuilder by copying an existing Attitude instance.
   * @param other The existing instance to copy.
   * @return A new Attitude RecordBuilder
   */
  public static eu.rawfie.uxv.Attitude.Builder newBuilder(eu.rawfie.uxv.Attitude other) {
    return new eu.rawfie.uxv.Attitude.Builder(other);
  }

  /**
   * RecordBuilder for Attitude instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Attitude>
    implements org.apache.avro.data.RecordBuilder<Attitude> {

    private eu.rawfie.uxv.Header header;
    private eu.rawfie.uxv.Header.Builder headerBuilder;
    /** Rotation around the body's longitudinal axis */
    private float phi;
    /** Rotation around the body's lateral or transverse axis */
    private float theta;
    /** Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north */
    private float psi;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.uxv.Attitude.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (other.hasHeaderBuilder()) {
        this.headerBuilder = eu.rawfie.uxv.Header.newBuilder(other.getHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.phi)) {
        this.phi = data().deepCopy(fields()[1].schema(), other.phi);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.theta)) {
        this.theta = data().deepCopy(fields()[2].schema(), other.theta);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.psi)) {
        this.psi = data().deepCopy(fields()[3].schema(), other.psi);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Attitude instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.uxv.Attitude other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      this.headerBuilder = null;
      if (isValidValue(fields()[1], other.phi)) {
        this.phi = data().deepCopy(fields()[1].schema(), other.phi);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.theta)) {
        this.theta = data().deepCopy(fields()[2].schema(), other.theta);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.psi)) {
        this.psi = data().deepCopy(fields()[3].schema(), other.psi);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'header' field.
      * @return The value.
      */
    public eu.rawfie.uxv.Header getHeader() {
      return header;
    }

    /**
      * Sets the value of the 'header' field.
      * @param value The value of 'header'.
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder setHeader(eu.rawfie.uxv.Header value) {
      validate(fields()[0], value);
      this.headerBuilder = null;
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'header' field has been set.
      * @return True if the 'header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'header' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public eu.rawfie.uxv.Header.Builder getHeaderBuilder() {
      if (headerBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(eu.rawfie.uxv.Header.newBuilder(header));
        } else {
          setHeaderBuilder(eu.rawfie.uxv.Header.newBuilder());
        }
      }
      return headerBuilder;
    }

    /**
     * Sets the Builder instance for the 'header' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public eu.rawfie.uxv.Attitude.Builder setHeaderBuilder(eu.rawfie.uxv.Header.Builder value) {
      clearHeader();
      headerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'header' field has an active Builder instance
     * @return True if the 'header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return headerBuilder != null;
    }

    /**
      * Clears the value of the 'header' field.
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder clearHeader() {
      header = null;
      headerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'phi' field.
      * Rotation around the body's longitudinal axis
      * @return The value.
      */
    public java.lang.Float getPhi() {
      return phi;
    }

    /**
      * Sets the value of the 'phi' field.
      * Rotation around the body's longitudinal axis
      * @param value The value of 'phi'.
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder setPhi(float value) {
      validate(fields()[1], value);
      this.phi = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'phi' field has been set.
      * Rotation around the body's longitudinal axis
      * @return True if the 'phi' field has been set, false otherwise.
      */
    public boolean hasPhi() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'phi' field.
      * Rotation around the body's longitudinal axis
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder clearPhi() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'theta' field.
      * Rotation around the body's lateral or transverse axis
      * @return The value.
      */
    public java.lang.Float getTheta() {
      return theta;
    }

    /**
      * Sets the value of the 'theta' field.
      * Rotation around the body's lateral or transverse axis
      * @param value The value of 'theta'.
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder setTheta(float value) {
      validate(fields()[2], value);
      this.theta = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'theta' field has been set.
      * Rotation around the body's lateral or transverse axis
      * @return True if the 'theta' field has been set, false otherwise.
      */
    public boolean hasTheta() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'theta' field.
      * Rotation around the body's lateral or transverse axis
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder clearTheta() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'psi' field.
      * Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
      * @return The value.
      */
    public java.lang.Float getPsi() {
      return psi;
    }

    /**
      * Sets the value of the 'psi' field.
      * Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
      * @param value The value of 'psi'.
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder setPsi(float value) {
      validate(fields()[3], value);
      this.psi = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'psi' field has been set.
      * Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
      * @return True if the 'psi' field has been set, false otherwise.
      */
    public boolean hasPsi() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'psi' field.
      * Rotation around the body's vertical axis. A value of 0 means the body is oriented towards true north
      * @return This builder.
      */
    public eu.rawfie.uxv.Attitude.Builder clearPsi() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Attitude build() {
      try {
        Attitude record = new Attitude();
        if (headerBuilder != null) {
          record.header = this.headerBuilder.build();
        } else {
          record.header = fieldSetFlags()[0] ? this.header : (eu.rawfie.uxv.Header) defaultValue(fields()[0]);
        }
        record.phi = fieldSetFlags()[1] ? this.phi : (java.lang.Float) defaultValue(fields()[1]);
        record.theta = fieldSetFlags()[2] ? this.theta : (java.lang.Float) defaultValue(fields()[2]);
        record.psi = fieldSetFlags()[3] ? this.psi : (java.lang.Float) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
