/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CamTriggerEnum {
  ONCE, DISTANCE_INTERVAL, TIME_INTERVAL, STOP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CamTriggerEnum\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"ONCE\",\"DISTANCE_INTERVAL\",\"TIME_INTERVAL\",\"STOP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
