/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Sensor information */
@org.apache.avro.specific.AvroGenerated
public class SensorInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3405289740194597257L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorInfo\",\"namespace\":\"eu.rawfie.uxv\",\"doc\":\"Sensor information\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"Header\",\"fields\":[{\"name\":\"sourceSystem\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Canonical name of the originating system\"},{\"name\":\"sourceModule\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Canonical name of the module within a given system that originated the message\"},{\"name\":\"time\",\"type\":\"long\",\"doc\":\"Time elapsed since the Unix epoch\",\"unit\":\"ms\"}]}},{\"name\":\"vendor_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique vendor name\"},{\"name\":\"product_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique product name\"},{\"name\":\"serial\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Serial number\"},{\"name\":\"types\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"enum\",\"name\":\"SensorType\",\"symbols\":[\"CURRENT\",\"VOLTAGE\",\"TEMPERATURE\",\"CONDUCTIVITY\",\"SALINITY\",\"WATER_DENSITY\",\"SOUND_SPEED\",\"PRESSURE\",\"RGB_CAM\",\"RGBD_CAM\",\"LIDAR\"]}},\"doc\":\"Array of quantities that the sensor is able to measure\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public eu.rawfie.uxv.Header header;
  /** Unique vendor name */
   public java.lang.String vendor_name;
  /** Unique product name */
   public java.lang.String product_name;
  /** Serial number */
   public java.lang.String serial;
  /** Array of quantities that the sensor is able to measure */
   public java.util.List<eu.rawfie.uxv.SensorType> types;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorInfo() {}

  /**
   * All-args constructor.
   * @param header The new value for header
   * @param vendor_name Unique vendor name
   * @param product_name Unique product name
   * @param serial Serial number
   * @param types Array of quantities that the sensor is able to measure
   */
  public SensorInfo(eu.rawfie.uxv.Header header, java.lang.String vendor_name, java.lang.String product_name, java.lang.String serial, java.util.List<eu.rawfie.uxv.SensorType> types) {
    this.header = header;
    this.vendor_name = vendor_name;
    this.product_name = product_name;
    this.serial = serial;
    this.types = types;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    case 1: return vendor_name;
    case 2: return product_name;
    case 3: return serial;
    case 4: return types;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (eu.rawfie.uxv.Header)value$; break;
    case 1: vendor_name = (java.lang.String)value$; break;
    case 2: product_name = (java.lang.String)value$; break;
    case 3: serial = (java.lang.String)value$; break;
    case 4: types = (java.util.List<eu.rawfie.uxv.SensorType>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'header' field.
   * @return The value of the 'header' field.
   */
  public eu.rawfie.uxv.Header getHeader() {
    return header;
  }

  /**
   * Sets the value of the 'header' field.
   * @param value the value to set.
   */
  public void setHeader(eu.rawfie.uxv.Header value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'vendor_name' field.
   * @return Unique vendor name
   */
  public java.lang.String getVendorName() {
    return vendor_name;
  }

  /**
   * Sets the value of the 'vendor_name' field.
   * Unique vendor name
   * @param value the value to set.
   */
  public void setVendorName(java.lang.String value) {
    this.vendor_name = value;
  }

  /**
   * Gets the value of the 'product_name' field.
   * @return Unique product name
   */
  public java.lang.String getProductName() {
    return product_name;
  }

  /**
   * Sets the value of the 'product_name' field.
   * Unique product name
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'serial' field.
   * @return Serial number
   */
  public java.lang.String getSerial() {
    return serial;
  }

  /**
   * Sets the value of the 'serial' field.
   * Serial number
   * @param value the value to set.
   */
  public void setSerial(java.lang.String value) {
    this.serial = value;
  }

  /**
   * Gets the value of the 'types' field.
   * @return Array of quantities that the sensor is able to measure
   */
  public java.util.List<eu.rawfie.uxv.SensorType> getTypes() {
    return types;
  }

  /**
   * Sets the value of the 'types' field.
   * Array of quantities that the sensor is able to measure
   * @param value the value to set.
   */
  public void setTypes(java.util.List<eu.rawfie.uxv.SensorType> value) {
    this.types = value;
  }

  /**
   * Creates a new SensorInfo RecordBuilder.
   * @return A new SensorInfo RecordBuilder
   */
  public static eu.rawfie.uxv.SensorInfo.Builder newBuilder() {
    return new eu.rawfie.uxv.SensorInfo.Builder();
  }

  /**
   * Creates a new SensorInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorInfo RecordBuilder
   */
  public static eu.rawfie.uxv.SensorInfo.Builder newBuilder(eu.rawfie.uxv.SensorInfo.Builder other) {
    return new eu.rawfie.uxv.SensorInfo.Builder(other);
  }

  /**
   * Creates a new SensorInfo RecordBuilder by copying an existing SensorInfo instance.
   * @param other The existing instance to copy.
   * @return A new SensorInfo RecordBuilder
   */
  public static eu.rawfie.uxv.SensorInfo.Builder newBuilder(eu.rawfie.uxv.SensorInfo other) {
    return new eu.rawfie.uxv.SensorInfo.Builder(other);
  }

  /**
   * RecordBuilder for SensorInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorInfo>
    implements org.apache.avro.data.RecordBuilder<SensorInfo> {

    private eu.rawfie.uxv.Header header;
    private eu.rawfie.uxv.Header.Builder headerBuilder;
    /** Unique vendor name */
    private java.lang.String vendor_name;
    /** Unique product name */
    private java.lang.String product_name;
    /** Serial number */
    private java.lang.String serial;
    /** Array of quantities that the sensor is able to measure */
    private java.util.List<eu.rawfie.uxv.SensorType> types;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.uxv.SensorInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (other.hasHeaderBuilder()) {
        this.headerBuilder = eu.rawfie.uxv.Header.newBuilder(other.getHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.vendor_name)) {
        this.vendor_name = data().deepCopy(fields()[1].schema(), other.vendor_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.product_name)) {
        this.product_name = data().deepCopy(fields()[2].schema(), other.product_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.serial)) {
        this.serial = data().deepCopy(fields()[3].schema(), other.serial);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.types)) {
        this.types = data().deepCopy(fields()[4].schema(), other.types);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SensorInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.uxv.SensorInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      this.headerBuilder = null;
      if (isValidValue(fields()[1], other.vendor_name)) {
        this.vendor_name = data().deepCopy(fields()[1].schema(), other.vendor_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.product_name)) {
        this.product_name = data().deepCopy(fields()[2].schema(), other.product_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.serial)) {
        this.serial = data().deepCopy(fields()[3].schema(), other.serial);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.types)) {
        this.types = data().deepCopy(fields()[4].schema(), other.types);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'header' field.
      * @return The value.
      */
    public eu.rawfie.uxv.Header getHeader() {
      return header;
    }

    /**
      * Sets the value of the 'header' field.
      * @param value The value of 'header'.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder setHeader(eu.rawfie.uxv.Header value) {
      validate(fields()[0], value);
      this.headerBuilder = null;
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'header' field has been set.
      * @return True if the 'header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'header' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public eu.rawfie.uxv.Header.Builder getHeaderBuilder() {
      if (headerBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(eu.rawfie.uxv.Header.newBuilder(header));
        } else {
          setHeaderBuilder(eu.rawfie.uxv.Header.newBuilder());
        }
      }
      return headerBuilder;
    }

    /**
     * Sets the Builder instance for the 'header' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public eu.rawfie.uxv.SensorInfo.Builder setHeaderBuilder(eu.rawfie.uxv.Header.Builder value) {
      clearHeader();
      headerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'header' field has an active Builder instance
     * @return True if the 'header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return headerBuilder != null;
    }

    /**
      * Clears the value of the 'header' field.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder clearHeader() {
      header = null;
      headerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'vendor_name' field.
      * Unique vendor name
      * @return The value.
      */
    public java.lang.String getVendorName() {
      return vendor_name;
    }

    /**
      * Sets the value of the 'vendor_name' field.
      * Unique vendor name
      * @param value The value of 'vendor_name'.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder setVendorName(java.lang.String value) {
      validate(fields()[1], value);
      this.vendor_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'vendor_name' field has been set.
      * Unique vendor name
      * @return True if the 'vendor_name' field has been set, false otherwise.
      */
    public boolean hasVendorName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'vendor_name' field.
      * Unique vendor name
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder clearVendorName() {
      vendor_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_name' field.
      * Unique product name
      * @return The value.
      */
    public java.lang.String getProductName() {
      return product_name;
    }

    /**
      * Sets the value of the 'product_name' field.
      * Unique product name
      * @param value The value of 'product_name'.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder setProductName(java.lang.String value) {
      validate(fields()[2], value);
      this.product_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'product_name' field has been set.
      * Unique product name
      * @return True if the 'product_name' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'product_name' field.
      * Unique product name
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'serial' field.
      * Serial number
      * @return The value.
      */
    public java.lang.String getSerial() {
      return serial;
    }

    /**
      * Sets the value of the 'serial' field.
      * Serial number
      * @param value The value of 'serial'.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder setSerial(java.lang.String value) {
      validate(fields()[3], value);
      this.serial = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'serial' field has been set.
      * Serial number
      * @return True if the 'serial' field has been set, false otherwise.
      */
    public boolean hasSerial() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'serial' field.
      * Serial number
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder clearSerial() {
      serial = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'types' field.
      * Array of quantities that the sensor is able to measure
      * @return The value.
      */
    public java.util.List<eu.rawfie.uxv.SensorType> getTypes() {
      return types;
    }

    /**
      * Sets the value of the 'types' field.
      * Array of quantities that the sensor is able to measure
      * @param value The value of 'types'.
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder setTypes(java.util.List<eu.rawfie.uxv.SensorType> value) {
      validate(fields()[4], value);
      this.types = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'types' field has been set.
      * Array of quantities that the sensor is able to measure
      * @return True if the 'types' field has been set, false otherwise.
      */
    public boolean hasTypes() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'types' field.
      * Array of quantities that the sensor is able to measure
      * @return This builder.
      */
    public eu.rawfie.uxv.SensorInfo.Builder clearTypes() {
      types = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public SensorInfo build() {
      try {
        SensorInfo record = new SensorInfo();
        if (headerBuilder != null) {
          record.header = this.headerBuilder.build();
        } else {
          record.header = fieldSetFlags()[0] ? this.header : (eu.rawfie.uxv.Header) defaultValue(fields()[0]);
        }
        record.vendor_name = fieldSetFlags()[1] ? this.vendor_name : (java.lang.String) defaultValue(fields()[1]);
        record.product_name = fieldSetFlags()[2] ? this.product_name : (java.lang.String) defaultValue(fields()[2]);
        record.serial = fieldSetFlags()[3] ? this.serial : (java.lang.String) defaultValue(fields()[3]);
        record.types = fieldSetFlags()[4] ? this.types : (java.util.List<eu.rawfie.uxv.SensorType>) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
