/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SensorType {
  CURRENT, VOLTAGE, TEMPERATURE, CONDUCTIVITY, SALINITY, WATER_DENSITY, SOUND_SPEED, PRESSURE, RGB_CAM, RGBD_CAM, LIDAR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SensorType\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"CURRENT\",\"VOLTAGE\",\"TEMPERATURE\",\"CONDUCTIVITY\",\"SALINITY\",\"WATER_DENSITY\",\"SOUND_SPEED\",\"PRESSURE\",\"RGB_CAM\",\"RGBD_CAM\",\"LIDAR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
