/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UAVNotificationEnum {
  ARM_OK, NOT_ARMED, TAKEOFF_OK, GOTO_OK, RTL_OK, ABORT_OK, INVALID_COMMAND, AUTO_ABORT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UAVNotificationEnum\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"ARM_OK\",\"NOT_ARMED\",\"TAKEOFF_OK\",\"GOTO_OK\",\"RTL_OK\",\"ABORT_OK\",\"INVALID_COMMAND\",\"AUTO_ABORT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
