/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Unit {
  AMPERE, CELSIUS, VOLT, BIT, BYTE, KILOGRAM, DECIBEL, KELVIN, PASCAL, HERTZ, METER, METER_PER_SECOND, METER_PER_SECOND_PER_SECOND, SECOND, SIEMENS_PER_METER, NTU, NEWTON, PERCENT, PARTS_PER_MILLION, PARTS_PER_BILLION, PSU, RADIAN, RADIAN_PER_SECOND, ROTATION_PER_MINUTE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Unit\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"AMPERE\",\"CELSIUS\",\"VOLT\",\"BIT\",\"BYTE\",\"KILOGRAM\",\"DECIBEL\",\"KELVIN\",\"PASCAL\",\"HERTZ\",\"METER\",\"METER_PER_SECOND\",\"METER_PER_SECOND_PER_SECOND\",\"SECOND\",\"SIEMENS_PER_METER\",\"NTU\",\"NEWTON\",\"PERCENT\",\"PARTS_PER_MILLION\",\"PARTS_PER_BILLION\",\"PSU\",\"RADIAN\",\"RADIAN_PER_SECOND\",\"ROTATION_PER_MINUTE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
