/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UxVOrientationEnum {
  ROTATION_NONE, ROTATION_YAW_45, ROTATION_YAW_90, ROTATION_YAW_135, ROTATION_YAW_180, ROTATION_YAW_225, ROTATION_YAW_270, ROTATION_YAW_315, ROTATION_PITCH_90, ROTATION_PITCH_270  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UxVOrientationEnum\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"ROTATION_NONE\",\"ROTATION_YAW_45\",\"ROTATION_YAW_90\",\"ROTATION_YAW_135\",\"ROTATION_YAW_180\",\"ROTATION_YAW_225\",\"ROTATION_YAW_270\",\"ROTATION_YAW_315\",\"ROTATION_PITCH_90\",\"ROTATION_PITCH_270\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
