/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.general.service.types;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AlgorithmTypeEnum {
  average, maximum, minimum, datareporting  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlgorithmTypeEnum\",\"namespace\":\"eu.rawfie.general.service.types\",\"symbols\":[\"average\",\"maximum\",\"minimum\",\"datareporting\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
