/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.general.service.types;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExperimentLaunchRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5528565726431657077L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExperimentLaunchRequest\",\"namespace\":\"eu.rawfie.general.service.types\",\"fields\":[{\"name\":\"executionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"testbedId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String executionId;
   public java.lang.String testbedId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExperimentLaunchRequest() {}

  /**
   * All-args constructor.
   * @param executionId The new value for executionId
   * @param testbedId The new value for testbedId
   */
  public ExperimentLaunchRequest(java.lang.String executionId, java.lang.String testbedId) {
    this.executionId = executionId;
    this.testbedId = testbedId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return executionId;
    case 1: return testbedId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: executionId = (java.lang.String)value$; break;
    case 1: testbedId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'executionId' field.
   * @return The value of the 'executionId' field.
   */
  public java.lang.String getExecutionId() {
    return executionId;
  }

  /**
   * Sets the value of the 'executionId' field.
   * @param value the value to set.
   */
  public void setExecutionId(java.lang.String value) {
    this.executionId = value;
  }

  /**
   * Gets the value of the 'testbedId' field.
   * @return The value of the 'testbedId' field.
   */
  public java.lang.String getTestbedId() {
    return testbedId;
  }

  /**
   * Sets the value of the 'testbedId' field.
   * @param value the value to set.
   */
  public void setTestbedId(java.lang.String value) {
    this.testbedId = value;
  }

  /**
   * Creates a new ExperimentLaunchRequest RecordBuilder.
   * @return A new ExperimentLaunchRequest RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder newBuilder() {
    return new eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder();
  }

  /**
   * Creates a new ExperimentLaunchRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExperimentLaunchRequest RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder newBuilder(eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder other) {
    return new eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder(other);
  }

  /**
   * Creates a new ExperimentLaunchRequest RecordBuilder by copying an existing ExperimentLaunchRequest instance.
   * @param other The existing instance to copy.
   * @return A new ExperimentLaunchRequest RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder newBuilder(eu.rawfie.general.service.types.ExperimentLaunchRequest other) {
    return new eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder(other);
  }

  /**
   * RecordBuilder for ExperimentLaunchRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExperimentLaunchRequest>
    implements org.apache.avro.data.RecordBuilder<ExperimentLaunchRequest> {

    private java.lang.String executionId;
    private java.lang.String testbedId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.executionId)) {
        this.executionId = data().deepCopy(fields()[0].schema(), other.executionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.testbedId)) {
        this.testbedId = data().deepCopy(fields()[1].schema(), other.testbedId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ExperimentLaunchRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.general.service.types.ExperimentLaunchRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.executionId)) {
        this.executionId = data().deepCopy(fields()[0].schema(), other.executionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.testbedId)) {
        this.testbedId = data().deepCopy(fields()[1].schema(), other.testbedId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'executionId' field.
      * @return The value.
      */
    public java.lang.String getExecutionId() {
      return executionId;
    }

    /**
      * Sets the value of the 'executionId' field.
      * @param value The value of 'executionId'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder setExecutionId(java.lang.String value) {
      validate(fields()[0], value);
      this.executionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'executionId' field has been set.
      * @return True if the 'executionId' field has been set, false otherwise.
      */
    public boolean hasExecutionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'executionId' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder clearExecutionId() {
      executionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'testbedId' field.
      * @return The value.
      */
    public java.lang.String getTestbedId() {
      return testbedId;
    }

    /**
      * Sets the value of the 'testbedId' field.
      * @param value The value of 'testbedId'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder setTestbedId(java.lang.String value) {
      validate(fields()[1], value);
      this.testbedId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'testbedId' field has been set.
      * @return True if the 'testbedId' field has been set, false otherwise.
      */
    public boolean hasTestbedId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'testbedId' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentLaunchRequest.Builder clearTestbedId() {
      testbedId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ExperimentLaunchRequest build() {
      try {
        ExperimentLaunchRequest record = new ExperimentLaunchRequest();
        record.executionId = fieldSetFlags()[0] ? this.executionId : (java.lang.String) defaultValue(fields()[0]);
        record.testbedId = fieldSetFlags()[1] ? this.testbedId : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
