/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.general.service.types;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExperimentStatusMsg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2208170932635275067L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExperimentStatusMsg\",\"namespace\":\"eu.rawfie.general.service.types\",\"fields\":[{\"name\":\"executionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ExperimentStatusEnum\",\"symbols\":[\"BOOKED\",\"ONGOING\",\"CHANGED\",\"COMPLETED\",\"BLOCKED\",\"CANCELED\",\"FAILED\"]}},{\"name\":\"testbedId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"CustomEncoding\":\"DateAsLongEncoding\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String executionId;
   public eu.rawfie.general.service.types.ExperimentStatusEnum status;
   public java.lang.String testbedId;
   public long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExperimentStatusMsg() {}

  /**
   * All-args constructor.
   * @param executionId The new value for executionId
   * @param status The new value for status
   * @param testbedId The new value for testbedId
   * @param timestamp The new value for timestamp
   */
  public ExperimentStatusMsg(java.lang.String executionId, eu.rawfie.general.service.types.ExperimentStatusEnum status, java.lang.String testbedId, java.lang.Long timestamp) {
    this.executionId = executionId;
    this.status = status;
    this.testbedId = testbedId;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return executionId;
    case 1: return status;
    case 2: return testbedId;
    case 3: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: executionId = (java.lang.String)value$; break;
    case 1: status = (eu.rawfie.general.service.types.ExperimentStatusEnum)value$; break;
    case 2: testbedId = (java.lang.String)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'executionId' field.
   * @return The value of the 'executionId' field.
   */
  public java.lang.String getExecutionId() {
    return executionId;
  }

  /**
   * Sets the value of the 'executionId' field.
   * @param value the value to set.
   */
  public void setExecutionId(java.lang.String value) {
    this.executionId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public eu.rawfie.general.service.types.ExperimentStatusEnum getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(eu.rawfie.general.service.types.ExperimentStatusEnum value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'testbedId' field.
   * @return The value of the 'testbedId' field.
   */
  public java.lang.String getTestbedId() {
    return testbedId;
  }

  /**
   * Sets the value of the 'testbedId' field.
   * @param value the value to set.
   */
  public void setTestbedId(java.lang.String value) {
    this.testbedId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new ExperimentStatusMsg RecordBuilder.
   * @return A new ExperimentStatusMsg RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentStatusMsg.Builder newBuilder() {
    return new eu.rawfie.general.service.types.ExperimentStatusMsg.Builder();
  }

  /**
   * Creates a new ExperimentStatusMsg RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExperimentStatusMsg RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentStatusMsg.Builder newBuilder(eu.rawfie.general.service.types.ExperimentStatusMsg.Builder other) {
    return new eu.rawfie.general.service.types.ExperimentStatusMsg.Builder(other);
  }

  /**
   * Creates a new ExperimentStatusMsg RecordBuilder by copying an existing ExperimentStatusMsg instance.
   * @param other The existing instance to copy.
   * @return A new ExperimentStatusMsg RecordBuilder
   */
  public static eu.rawfie.general.service.types.ExperimentStatusMsg.Builder newBuilder(eu.rawfie.general.service.types.ExperimentStatusMsg other) {
    return new eu.rawfie.general.service.types.ExperimentStatusMsg.Builder(other);
  }

  /**
   * RecordBuilder for ExperimentStatusMsg instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExperimentStatusMsg>
    implements org.apache.avro.data.RecordBuilder<ExperimentStatusMsg> {

    private java.lang.String executionId;
    private eu.rawfie.general.service.types.ExperimentStatusEnum status;
    private java.lang.String testbedId;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.general.service.types.ExperimentStatusMsg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.executionId)) {
        this.executionId = data().deepCopy(fields()[0].schema(), other.executionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.testbedId)) {
        this.testbedId = data().deepCopy(fields()[2].schema(), other.testbedId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ExperimentStatusMsg instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.general.service.types.ExperimentStatusMsg other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.executionId)) {
        this.executionId = data().deepCopy(fields()[0].schema(), other.executionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.testbedId)) {
        this.testbedId = data().deepCopy(fields()[2].schema(), other.testbedId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'executionId' field.
      * @return The value.
      */
    public java.lang.String getExecutionId() {
      return executionId;
    }

    /**
      * Sets the value of the 'executionId' field.
      * @param value The value of 'executionId'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder setExecutionId(java.lang.String value) {
      validate(fields()[0], value);
      this.executionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'executionId' field has been set.
      * @return True if the 'executionId' field has been set, false otherwise.
      */
    public boolean hasExecutionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'executionId' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder clearExecutionId() {
      executionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public eu.rawfie.general.service.types.ExperimentStatusEnum getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder setStatus(eu.rawfie.general.service.types.ExperimentStatusEnum value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'testbedId' field.
      * @return The value.
      */
    public java.lang.String getTestbedId() {
      return testbedId;
    }

    /**
      * Sets the value of the 'testbedId' field.
      * @param value The value of 'testbedId'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder setTestbedId(java.lang.String value) {
      validate(fields()[2], value);
      this.testbedId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'testbedId' field has been set.
      * @return True if the 'testbedId' field has been set, false otherwise.
      */
    public boolean hasTestbedId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'testbedId' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder clearTestbedId() {
      testbedId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.ExperimentStatusMsg.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ExperimentStatusMsg build() {
      try {
        ExperimentStatusMsg record = new ExperimentStatusMsg();
        record.executionId = fieldSetFlags()[0] ? this.executionId : (java.lang.String) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (eu.rawfie.general.service.types.ExperimentStatusEnum) defaultValue(fields()[1]);
        record.testbedId = fieldSetFlags()[2] ? this.testbedId : (java.lang.String) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
