/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.general.service.types;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum RCHealthStatusEnum {
  OK, WARNING, CRITICAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RCHealthStatusEnum\",\"namespace\":\"eu.rawfie.general.service.types\",\"symbols\":[\"OK\",\"WARNING\",\"CRITICAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
