/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.general.service.types;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TestbedServicesHealthStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6083270636305983348L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TestbedServicesHealthStatus\",\"namespace\":\"eu.rawfie.general.service.types\",\"fields\":[{\"name\":\"testbed_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"component_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"msg_timestamp\",\"type\":{\"type\":\"long\",\"CustomEncoding\":\"DateAsLongEncoding\"}},{\"name\":\"health_status\",\"type\":{\"type\":\"enum\",\"name\":\"TestbedServicesHealthStatusEnum\",\"symbols\":[\"OK\",\"WARNING\",\"CRITICAL\"]}},{\"name\":\"message\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"String containing the details of the current status\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String testbed_id;
   public java.lang.String component_name;
   public long msg_timestamp;
   public eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum health_status;
  /** String containing the details of the current status */
   public java.lang.String message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TestbedServicesHealthStatus() {}

  /**
   * All-args constructor.
   * @param testbed_id The new value for testbed_id
   * @param component_name The new value for component_name
   * @param msg_timestamp The new value for msg_timestamp
   * @param health_status The new value for health_status
   * @param message String containing the details of the current status
   */
  public TestbedServicesHealthStatus(java.lang.String testbed_id, java.lang.String component_name, java.lang.Long msg_timestamp, eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum health_status, java.lang.String message) {
    this.testbed_id = testbed_id;
    this.component_name = component_name;
    this.msg_timestamp = msg_timestamp;
    this.health_status = health_status;
    this.message = message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return testbed_id;
    case 1: return component_name;
    case 2: return msg_timestamp;
    case 3: return health_status;
    case 4: return message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: testbed_id = (java.lang.String)value$; break;
    case 1: component_name = (java.lang.String)value$; break;
    case 2: msg_timestamp = (java.lang.Long)value$; break;
    case 3: health_status = (eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum)value$; break;
    case 4: message = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'testbed_id' field.
   * @return The value of the 'testbed_id' field.
   */
  public java.lang.String getTestbedId() {
    return testbed_id;
  }

  /**
   * Sets the value of the 'testbed_id' field.
   * @param value the value to set.
   */
  public void setTestbedId(java.lang.String value) {
    this.testbed_id = value;
  }

  /**
   * Gets the value of the 'component_name' field.
   * @return The value of the 'component_name' field.
   */
  public java.lang.String getComponentName() {
    return component_name;
  }

  /**
   * Sets the value of the 'component_name' field.
   * @param value the value to set.
   */
  public void setComponentName(java.lang.String value) {
    this.component_name = value;
  }

  /**
   * Gets the value of the 'msg_timestamp' field.
   * @return The value of the 'msg_timestamp' field.
   */
  public java.lang.Long getMsgTimestamp() {
    return msg_timestamp;
  }

  /**
   * Sets the value of the 'msg_timestamp' field.
   * @param value the value to set.
   */
  public void setMsgTimestamp(java.lang.Long value) {
    this.msg_timestamp = value;
  }

  /**
   * Gets the value of the 'health_status' field.
   * @return The value of the 'health_status' field.
   */
  public eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum getHealthStatus() {
    return health_status;
  }

  /**
   * Sets the value of the 'health_status' field.
   * @param value the value to set.
   */
  public void setHealthStatus(eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum value) {
    this.health_status = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return String containing the details of the current status
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * String containing the details of the current status
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Creates a new TestbedServicesHealthStatus RecordBuilder.
   * @return A new TestbedServicesHealthStatus RecordBuilder
   */
  public static eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder newBuilder() {
    return new eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder();
  }

  /**
   * Creates a new TestbedServicesHealthStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TestbedServicesHealthStatus RecordBuilder
   */
  public static eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder newBuilder(eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder other) {
    return new eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder(other);
  }

  /**
   * Creates a new TestbedServicesHealthStatus RecordBuilder by copying an existing TestbedServicesHealthStatus instance.
   * @param other The existing instance to copy.
   * @return A new TestbedServicesHealthStatus RecordBuilder
   */
  public static eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder newBuilder(eu.rawfie.general.service.types.TestbedServicesHealthStatus other) {
    return new eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder(other);
  }

  /**
   * RecordBuilder for TestbedServicesHealthStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TestbedServicesHealthStatus>
    implements org.apache.avro.data.RecordBuilder<TestbedServicesHealthStatus> {

    private java.lang.String testbed_id;
    private java.lang.String component_name;
    private long msg_timestamp;
    private eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum health_status;
    /** String containing the details of the current status */
    private java.lang.String message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.testbed_id)) {
        this.testbed_id = data().deepCopy(fields()[0].schema(), other.testbed_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.component_name)) {
        this.component_name = data().deepCopy(fields()[1].schema(), other.component_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_timestamp)) {
        this.msg_timestamp = data().deepCopy(fields()[2].schema(), other.msg_timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.health_status)) {
        this.health_status = data().deepCopy(fields()[3].schema(), other.health_status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.message)) {
        this.message = data().deepCopy(fields()[4].schema(), other.message);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TestbedServicesHealthStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.general.service.types.TestbedServicesHealthStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.testbed_id)) {
        this.testbed_id = data().deepCopy(fields()[0].schema(), other.testbed_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.component_name)) {
        this.component_name = data().deepCopy(fields()[1].schema(), other.component_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_timestamp)) {
        this.msg_timestamp = data().deepCopy(fields()[2].schema(), other.msg_timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.health_status)) {
        this.health_status = data().deepCopy(fields()[3].schema(), other.health_status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.message)) {
        this.message = data().deepCopy(fields()[4].schema(), other.message);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'testbed_id' field.
      * @return The value.
      */
    public java.lang.String getTestbedId() {
      return testbed_id;
    }

    /**
      * Sets the value of the 'testbed_id' field.
      * @param value The value of 'testbed_id'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder setTestbedId(java.lang.String value) {
      validate(fields()[0], value);
      this.testbed_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'testbed_id' field has been set.
      * @return True if the 'testbed_id' field has been set, false otherwise.
      */
    public boolean hasTestbedId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'testbed_id' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder clearTestbedId() {
      testbed_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'component_name' field.
      * @return The value.
      */
    public java.lang.String getComponentName() {
      return component_name;
    }

    /**
      * Sets the value of the 'component_name' field.
      * @param value The value of 'component_name'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder setComponentName(java.lang.String value) {
      validate(fields()[1], value);
      this.component_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'component_name' field has been set.
      * @return True if the 'component_name' field has been set, false otherwise.
      */
    public boolean hasComponentName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'component_name' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder clearComponentName() {
      component_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'msg_timestamp' field.
      * @return The value.
      */
    public java.lang.Long getMsgTimestamp() {
      return msg_timestamp;
    }

    /**
      * Sets the value of the 'msg_timestamp' field.
      * @param value The value of 'msg_timestamp'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder setMsgTimestamp(long value) {
      validate(fields()[2], value);
      this.msg_timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'msg_timestamp' field has been set.
      * @return True if the 'msg_timestamp' field has been set, false otherwise.
      */
    public boolean hasMsgTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'msg_timestamp' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder clearMsgTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'health_status' field.
      * @return The value.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum getHealthStatus() {
      return health_status;
    }

    /**
      * Sets the value of the 'health_status' field.
      * @param value The value of 'health_status'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder setHealthStatus(eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum value) {
      validate(fields()[3], value);
      this.health_status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'health_status' field has been set.
      * @return True if the 'health_status' field has been set, false otherwise.
      */
    public boolean hasHealthStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'health_status' field.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder clearHealthStatus() {
      health_status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * String containing the details of the current status
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * String containing the details of the current status
      * @param value The value of 'message'.
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder setMessage(java.lang.String value) {
      validate(fields()[4], value);
      this.message = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * String containing the details of the current status
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'message' field.
      * String containing the details of the current status
      * @return This builder.
      */
    public eu.rawfie.general.service.types.TestbedServicesHealthStatus.Builder clearMessage() {
      message = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public TestbedServicesHealthStatus build() {
      try {
        TestbedServicesHealthStatus record = new TestbedServicesHealthStatus();
        record.testbed_id = fieldSetFlags()[0] ? this.testbed_id : (java.lang.String) defaultValue(fields()[0]);
        record.component_name = fieldSetFlags()[1] ? this.component_name : (java.lang.String) defaultValue(fields()[1]);
        record.msg_timestamp = fieldSetFlags()[2] ? this.msg_timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.health_status = fieldSetFlags()[3] ? this.health_status : (eu.rawfie.general.service.types.TestbedServicesHealthStatusEnum) defaultValue(fields()[3]);
        record.message = fieldSetFlags()[4] ? this.message : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
